import operator

from typing import Annotated
from typing import TypedDict


class SearchResult(TypedDict):

    query: str

    title: str

    url: str

    snippet: str


class ResearchState(TypedDict):

    # User request
    topic: str

    # Queries generated by agent
    search_queries: list[str]

    # Queries waiting for execution
    pending_queries: list[str]

    # All accumulated web results
    search_results: Annotated[
        list[SearchResult],
        operator.add
    ]

    # Number of research loops
    loop_count: int

    # Quality decision
    is_sufficient: bool

    # Explanation from evaluator
    evaluation_reason: str

    # Information still missing
    missing_information: str

    # Final generated report
    final_report: str